### ISSUE TITLE
Adding CLI commands for ops

### ISSUE THREAD

**Issue by longfin** [planetarium/NineChronicles.EthBridge#237]
There is already [Gnosis safe Web UI](https://app.safe.global/) but in some setups with incompatible environments(such as AWS KMS), we can't leverage it and should write and execute ad-hoc scripts. 

So it would be helpful if we get commands to send manual transactions (proposal and/or execute) via CLI.

**Comment by shkangr** [comment]
resolved by: #247

**Comment by shkangr** [comment]
resolved by: #247
